### ISSUE TITLE
wrong position of volume controller in safari

### ISSUE THREAD

**Issue by airyland** [hilongjw/vue-video#1]
<img width="1070" alt="2016-06-25 12 08 06" src="https://cloud.githubusercontent.com/assets/559179/16343462/defb67fa-3a69-11e6-9cbe-c27eef8b935e.png">

and there is also a typo mistake in title: `vdeo`

**Comment by hilongjw** [comment]
I also found this bug with android browser, I'll fix it tomorrow

**Comment by hilongjw** [comment]
and vdeo is not a spelling mistake, it is project code name ('・ω・')

**Comment by hilongjw** [comment]
fixed, https://github.com/hilongjw/vue-video/commit/5bab96c41051648bd81d6d982757e28f2980b2ae
